apiVersion: apps/v1
kind: Deployment
metadata:
  name: micropro-deployment
  namespace: feed-objstore-poc
  labels:
    app: micropro
spec:
  replicas: 2
  selector:
    matchLabels:
      app: micropro
  template:
    metadata:
      labels:
        app: micropro
    spec:
      containers:
        - name: micropro
          image: artifactory-master.cdaas.oraclecloud.com/docker-cxsales-dev/cxsales/sales-common/cxsales/mittupoc:test1
          ports:
            - containerPort: 8080
          env:

---
apiVersion: v1
kind: Service
metadata:
  name: micropro-service
  namespace: feed-objstore-poc
spec:
  type: NodePort
  selector:
    app: micropro
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 31000