apiVersion: apps/v1
kind: Deployment
metadata:
  name: micropro-deployment
  labels:
    app: micropro
spec:
  replicas: 3
  selector:
    matchLabels:
      app: micropro
  template:
    metadata:
      labels:
        app: micropro
    spec:
      containers:
        - name: micropro
          image: mittuthomasoracle/micropro
          ports:
            - containerPort: 8080
          env:

---
apiVersion: v1
kind: Service
metadata:
  name: micropro-service
spec:
  type: NodePort
  selector:
    app: micropro
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 31000